SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `collection` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `auth_user` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `role` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `item` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE `user_type` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;

DROP TABLE `OPENJPA_SEQUENCE_TABLE`;

SET FOREIGN_KEY_CHECKS=1;
